name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
      - name: Compile
        shell: bash
        run: |
          echo "Running command: cmake -DRUN_COVERAGE=1 .. && make -j2"
          mkdir -p build && cd build
          cmake -DRUN_COVERAGE=1 .. && make -j2
