name: "Doc check"
description: "Code documentation generation with Doxygen"

inputs:
  path:
    required: true
    description: "Path to validate"
    default: .

runs:
  using: "composite"
  steps:
    - name: "Generate documentation"
      shell: bash
      run: |
          # We only make check, not changes
          DOX_CONF_FILE=${{ inputs.path }}/Doxyfile

          {
              cat $DOX_CONF_FILE
              echo "OUTPUT_DIRECTORY = ${{ inputs.path }}/doc"
              echo "INPUT" = ${{ inputs.path }}/src ${{ inputs.path }}/include
          } > $DOX_CONF_FILE

          # Generate documentation
          sudo dot -c

          ERROR_FILE_FLAG=${{ inputs.path }}/dox_errors.txt

          doxygen -s ${CONFIG_FILE} 2> ${ERROR_FILE_FLAG}

          if [ -s $ERROR_FILE_FLAG ]; then
              echo "Error: There are some files that are not documented correctly"
              cat $ERROR_FILE_FLAG
              exit 1
          else
              echo "All files are documented correctly. Niiiceee"
              exit 0
          fi
    # Upload errors as an artifact, when failed
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Doxygen errors!!!
        path: ${{ inputs.path }}/dox_errors.txt
        retention-days: 1

    - uses: actions/upload-artifact@v4
      if: success()
      with:
        name: Doxygen documentation
        path: ${{ inputs.path }}/doc
        retention-days: 1
